#!/bin/bash

# Automounter for removable media
udiskie &

# Wallpaper Backend
swww-daemon --format xrgb &

# Bar
waybar &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Notify about devices connecting and disconnecting
devify &

# Idle daemon to screen lock
hypridle &

# Clipboard
wl-paste --watch cliphist store &

# Screen sharing and portals
"$HOME"/.config/hypr/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Audio
easyeffects --gapplication-service &
